import type { TechnologyDetails } from '~~/shared/types/tech'

export const TECHNOLOGIES: TechnologyDetails = {
    html: ['HTML 5', 'html.svg', 'frontend'],
    vue: ['Vue', 'vue.svg', 'frontend'],
    nuxt: ['Nuxt', 'nuxt.svg', 'frontend'],
    react: ['React', 'react.svg', 'frontend'],
    next: ['NextJS', 'next.svg', 'frontend'],
    angular: ['Angular', 'angular.svg', 'frontend'],
    css: ['CSS 3', 'css.svg', 'frontend'],
    tailwind: ['Tailwind', 'tailwind.svg', 'frontend'],
    javascript: ['JavaScript', 'javascript.svg', 'frontend'],
    typescript: ['TypeScript', 'typescript.svg', 'frontend'],
    django: ['Django', 'django.svg', 'backend'],
    scala: ['Scala', 'scala.svg', 'backend'],
    csharp: ['C#', 'csharp.svg', 'backend'],
    dotnet: ['.Net', 'dotnet.svg', 'backend'],
    postgresql: ['PostgreSQL', 'postgresql.svg', 'backend'],
    godot: ['Godot', 'godot.svg', 'gamedev'],
    python: ['Python', 'python.svg', 'gamedev'],
    gimp: ['GIMP', 'gimp.svg', 'gamedev'],
    blender: ['Blender', 'blender.svg', 'gamedev'],
    gsap: ['GSAP', 'gsap.svg', 'animation'],
    motion: ['Motion', 'motion.svg', 'animation'],
    strapi: ['Strapi', 'strapi.svg', 'cms'],
    reactnative: ['React Native', 'react.svg', 'mobile'],
    github: ['Github', 'github.svg', 'infra'],
    azure: ['Azure', 'azure.svg', 'infra'],
    aws: ['AWS', 'aws.svg', 'infra'],
    gcp: ['GCP', 'gcp.svg', 'api'],
    discord: ['Discord', 'discord.svg', 'api'],
    zoho: ['Zoho', 'zoho.svg', 'api'],
}
